### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#737]
### v3

There are some rather immediate tasks we should just knock out. So I guess these are the v3 requirements/milestones:

- [ ] Consider an LTS strategy for v2 as people are not going upgrade to Babel 7 for several months.
- [ ] Fix Docker support HMR port issue @gregmartyn 
- [ ] Update to babel-preset-razzle for Babel 7
- [ ] Update .babelrc resolution to handle babel.config.js
- [ ] Bump up deps
- [ ] Upgrade Jest
- [ ] Backwards compat??

### v4
- [ ] Polish and push up internal @palmerhq source cache as plugin? 
- [ ] Modes.
  - `server` (perhaps we deprecate jaredpalmer/backpack) 😢 
  - `iso` the way stuff works now
  - `spa` (client-only) 
- [ ] Plugins
  - `server-artifact` This would include all node externals (ie `node_modules`) in a single javascript file (we do this @palmerhq and it's awesome)
- [ ] New docs
   - Docker
   - Polyfills
   - Authentication
   - Serverless?

### v5 
- [ ] New plugins
  - `serverless` Optimizations for serverless / lambda Razzle (need help here)
  - `binary` Make the final server output bytecode via something like Zeit's pkg?? Idk? Could be cool.
- [ ] Prerender script / Export
  - `razzle prerender --routes=routes.json`
- [ ] Explore Parcel modes now that it has full node.js support.
- [ ] Revisit multi-port setup/runtime dep, perhaps we can figure out how to mess with require cache + sockets

**Comment by gregmartyn** [comment]
A changelog would really help as these things get merged

**Comment by jaredpalmer** [comment]
I keep changelogs in release notes pretty religiously: https://github.com/jaredpalmer/razzle/releases

**Comment by gregmartyn** [comment]
#747

**Comment by olehreznichenko** [comment]
Sync code base with latest CRA?
Jest with puppeteer?

**Comment by xpromx** [comment]
Do you have a plan of when you are planning to release each version?
